### PR TITLE
[compute_instance] adding a variable to add/remove the hostname suffix

### PR DESCRIPTION
**Pull request by jeenx**

### CODE REVIEW

**Review by morgante — CHANGES_REQUESTED** [review]
Let's make this a boolean: `add_hostname_suffix`.

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by jeenx** [comment]
@morgante Thank you thats actually much better, also one of the builds keeps failing but I'm not able to see the build output.

**Review by morgante — APPROVED** [review]

**Comment by morgante** [comment]
> @morgante Thank you thats actually much better, also one of the builds keeps failing but I'm not able to see the build output.

Looks like it's working now. Thanks!

**Pull request merged**
