### PR TITLE
feat: mig labels & most disruptive update policy action update

### PR DESCRIPTION
**Pull request by rauny-brandao**
Adds support on mig to [most_disruptive_allowed_action](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_instance_group_manager#most_disruptive_allowed_action) and to [all_instances_config labels](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_instance_group_manager#all_instances_config)

To create this PR, I ran `make build`, which updated the `date` and set `defaultValue: null` in the metadata.yml files. Please let me know if I should keep them.

### CODE REVIEW

**Comment by g-awmalik** [comment]
@rauny-brandao - thanks for the PR. Can you please take a look at the lint failures?

**Comment by rauny-brandao** [comment]
@g-awmalik linting is fixed. Is there a way to see the failures for: `terraform-google-vm-int-trigger`?

**Comment by rauny-brandao** [comment]
@g-awmalik please let me know if we need something else for this to be merged, thank you!

**Review by g-awmalik — APPROVED** [review]

**Comment by jlenuffgsoi** [comment]
I think this because you want to be as much compliant as possible : https://github.com/terraform-google-modules/terraform-google-vm/blob/master/modules/mig/versions.tf#L18C3-L18C32
```hcl
...
terraform {
  required_version = ">=0.13.0"
...
```

**Pull request merged**
