### PR TITLE
feat(TF>=1.3)!: make mig health check fields optional

### LINKED ISSUE #153: FR: make fields of health_check optional
Currently all fields of mig.healthcheck is mandatory so one has to write a config below:

```
module "mig" {
  source                  = "terraform-google-modules/vm/google//modules/mig"
  version                 = "1.3.0"
  ...
  health_check = {
    type                = "http"
    initial_delay_sec   = 30
    check_interval_sec  = 5
    timeout_sec         = 5
    healthy_threshold   = 1
    unhealthy_threshold = 5
    response            = ""
    proxy_header        = "NONE"
    port                = 80
    request             = ""
    request_path        = "/"
    host                = ""
  }
}
```

It's quite verbose compared to plain `google_compute_health_check` which will be like
```
resource "google_compute_health_check" "my-service-http-health" {
  provider = google-beta
  name     = "my-service-http-health"

  initial_delay_sec   = 30
  check_interval_sec  = 5
  timeout_sec         = 5
  healthy_threshold   = 1
  unhealthy_threshold = 5

  http_health_check {
    port         = var.image_port
    request_path = "/healthz"
  }
}
```

It would be great if `modules/mig` can set sane default and make params optional

### PR DESCRIPTION
**Pull request by rauny-brandao**
This makes MIG health check fields optional, the default values comes from the variable `health_check`, closes #153

### CODE REVIEW

**Review by g-awmalik — CHANGES_REQUESTED** [review]
Thanks for the PR. Looks fine overall but needs a bump to the [required_version](https://github.com/terraform-google-modules/terraform-google-vm/blob/5e7f85c2866536e8f1663faefed6fcfd47f9e01c/autogen/versions.tf.tmpl#L18) for Terraform to >= 1.3.

**Comment by g-awmalik** [comment]
@rauny-brandao - I just realized that you haven't added any assertions for the healthcheck example that you modified. Can you please take a moment and add them [here](https://github.com/terraform-google-modules/terraform-google-vm/blob/e6bde772c30d47232a7ef3bc1a851db0e8a6032d/test/integration/mig_healthcheck/controls/mig_healthcheck.rb)?

**Comment by rauny-brandao** [comment]
up @g-awmalik

**Pull request closed without merging**
