### PR TITLE
Update versions.tf

### PR DESCRIPTION
**Pull request by cocktailer**

### CODE REVIEW

**Comment by MajorBreakfast** [comment]
@bharathkkb Please have a look at what the ci failure is. This PR adds support for Terraform 0.13 🎉

**Comment by bharathkkb** [comment]
@cocktailer @MajorBreakfast We will need to pin the build images in `int.cloudbuild.yaml` and `lint.cloudbuild.yaml `to `0.12.0` as not all external modules used in this has been updated. [Example](https://github.com/terraform-google-modules/terraform-google-project-factory/blob/bd2ed1734bf96ca77cc80816ed76892864668070/build/int.cloudbuild.yaml#L49)

**Comment by brandonjbjelland** [comment]
👋  @cocktailer and @MajorBreakfast  - I'm actually looking to make this same change but you beat me to the chase here. I'll give a few days for follow up here but if there's no movement I'll look to do the same work in a different PR if it burns into ealy next week. Thanks for the continued support here!

**Comment by brandonjbjelland** [comment]
Last opportunity to finish this out @cocktailer & @MajorBreakfast . I'll be opening a duplicate PR by EOD if this isn't resolved.

**Comment by bharathkkb** [comment]
Superseded by #108.

**Pull request closed without merging**
