### PR TITLE
feat!: support health check logging

### PR DESCRIPTION
**Pull request by ericyz**
Add a flag to enable or disable health check logging.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀
Unfortunately it looks like some of our CI checks failed. See the [Contributing Guide](../blob/master/CONTRIBUTING.md) for details.
- ⚠️check_terraform
 Failed Terraform check. More details below. 
 ```bash 
Running terraform fmt
Running terraform validate
terraform_validate ./examples/compute_instance/disk_snapshot 
Success!
 The configuration is valid.
terraform_validate ./examples/compute_instance/multiple_interfaces 
Success!
 The configuration is valid.
terraform_validate ./examples/compute_instance/next_hop 
Success!
 The configuration is valid.
terraform_validate ./examples/compute_instance/simple 
Success!
 The configuration is valid.
terraform_validate ./examples/compute_instance/tags 
Success!
 The configuration is valid.
terraform_validate ./examples/instance_template/additional_disks 
Success!
 The configuration is valid.
terraform_validate ./examples/instance_template/alias_ip_range 
Success!
 The configuration is valid.
terraform_validate ./examples/instance_template/encrypted_disks 
Success!
 The configuration is valid.
terraform_validate ./examples/instance_template/simple 
Success!
 The configuration is valid.
terraform_validate ./examples/mig/autoscaler 
Success!
 The configuration is valid.
terraform_validate ./examples/mig/full 
Success!
 The configuration is valid.
terraform_validate ./examples/mig/healthcheck 
╷
│
 
Error: 
Invalid value for module argument
│
 
│
 
  on main.tf line 80, in module "mig":
│
 
  80:   health_check = 
{
│
 
  81:     type                = "https"
│
 
  82:     initial_delay_sec   = 120
│
 
  83:     check_interval_sec  = 5
│
 
  84:     healthy_threshold   = 2
│
 
  85:     timeout_sec         = 5
│
 
  86:     unhealthy_threshold = 2
│
 
  87:     response            = ""
│
 
  88:     proxy_header        = "NONE"
│
 
  89:     port                = 443
│
 
  90:     request             = ""
│
 
  91:     request_path        = "/"
│
 
  92:     host                = "localhost"
│
 
  93:   }
│
 
│
 
The given value is not suitable for child module variable "health_check"
│
 
defined at ../../../modules/mig/variables.tf:103,1-24: attribute
│
 
"enable_logging" is required.
╵
terraform_validate ./examples/mig/simple 
Success!
 The configuration is valid.
terraform_validate ./examples/mig_with_percent/simple 
Success!
 The configuration is valid.
terraform_validate ./examples/preemptible_and_regular_instance_templates/simple 
Success!
 The configuration is valid.
terraform_validate ./examples/umig/full 
Success!
 The configuration is valid.
terraform_validate ./examples/umig/named_ports 
Success!
 The configuration is valid.
terraform_validate ./examples/umig/simple 
Success!
 The configuration is valid.
terraform_validate ./examples/umig/static_ips 
Success!
 The configuration is valid.
terraform_validate ./modules/compute_disk_snapshot 
Success!
 The configuration is valid.
terraform_validate ./modules/compute_instance 
Success!
 The configuration is valid.
terraform_validate ./modules/instance_template 
Success!
 The configuration is valid.
terraform_validate ./modules/mig 
Success!
 The configuration is valid.
terraform_validate ./modules/mig_with_percent 
Success!
 The configuration is valid.
terraform_validate ./modules/preemptible_and_regular_instance_templates 
Success!
 The configuration is valid.
terraform_validate ./modules/umig 
Success!
 The configuration is valid.
terraform_validate ./test/fixtures/compute_instance/disk_snapshot 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.2"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/compute_instance/simple_zone 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.2"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/instance_simple 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.2"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/instance_template/additional_disks 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.2"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/instance_template/alias_ip_range 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.2"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/instance_template/simple 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.2"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/mig/autoscaler 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.2"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/mig/healthcheck 
╷
│
 
Error: 
Invalid value for module argument
│
 
│
 
  on ../../../../examples/mig/healthcheck/main.tf line 80, in module "mig":
│
 
  80:   health_check = 
{
│
 
  81:     type                = "https"
│
 
  82:     initial_delay_sec   = 120
│
 
  83:     check_interval_sec  = 5
│
 
  84:     healthy_threshold   = 2
│
 
  85:     timeout_sec         = 5
│
 
  86:     unhealthy_threshold = 2
│
 
  87:     response            = ""
│
 
  88:     proxy_header        = "NONE"
│
 
  89:     port                = 443
│
 
  90:     request             = ""
│
 
  91:     request_path        = "/"
│
 
  92:     host                = "localhost"
│
 
  93:   }
│
 
│
 
The given value is not suitable for child module variable "health_check"
│
 
defined at ../../../../modules/mig/variables.tf:103,1-24: attribute
│
 
"enable_logging" is required.
╵
terraform_validate ./test/fixtures/mig/simple 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.2"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/mig_with_percent/simple 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.2"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/preemptible_and_regular_instance_templates/simple 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.2"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/umig/named_ports 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.2"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/umig/simple 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.2"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/fixtures/umig/static_ips 
╷
│
 
Warning: 
Version constraints inside provider configuration blocks are deprecated
│
 
│
 
  on network.tf line 18, in provider "random":
│
 
  18:   version = 
"~> 2.2"
│
 
│
 
Terraform 0.13 and earlier allowed provider version constraints inside the
│
 
provider configuration block, but that is now deprecated and will be
│
 
removed in a future version of Terraform. To silence this warning, move the
│
 
provider version constraint into the required_providers block.
╵
Success!
 The configuration is valid, but there were some
validation warnings as shown above.
terraform_validate ./test/setup 
Success!
 The configuration is valid.
 ```

**Comment by ericyz** [comment]
@bharathkkb - please review at your convenience

**Comment by ericyz** [comment]
@bharathkkb - I might need your help to review and provide feedback when you or other reviewers have a minute. Thank you.

**Review by bharathkkb — APPROVED** [review]
Thanks for the PR @ericyz

**Pull request merged**
