### PR TITLE
feat: Add Stack Type to Additional Interfaces for IPv6

### PR DESCRIPTION
**Pull request by thinkjk**
In order to use an IPv6 address as an additional interface you need to set the stack type at the additional interface level. Currently in the module it's only set at the main interface.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@thinkjk
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by thinkjk** [comment]
@apeabody is there anything else I have to do to get this PR approved?

**Review by apeabody — CHANGES_REQUESTED** [review]
Hi @thinkjk - Thanks for the contribution!  

I think it would be valuable to add a new `stack_type` variable to [`additional_networks`](https://github.com/terraform-google-modules/terraform-google-vm/blob/master/modules/instance_template/variables.tf#L196) and reference that (e.g. `network_interface.value.stack_type`) instead of the main networks `var.stack_type` to enable different stack types on each network as needed.

**Pull request closed without merging**
