### PR TITLE
feat: add spot instances

### LINKED ISSUE #259: Add support for spot instances
### TL;DR

This module supports preemptible instances, but not spot instances

### Terraform Resources

We should be able to use provisioning_model = SPOT to support spot instances: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_template#nested_scheduling

### Detailed design

Add a "spot" variable in the model and set the provisioning_model here: https://github.com/terraform-google-modules/terraform-google-vm/blob/dfb0523ef87d3c3b742b73bec8c6d4dc54aa3a7a/modules/instance_template/main.tf#L144-L149

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by llinros**
Adds option to use spot instances
fixes #259

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
@llinros
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@llinros
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by comment-bot-dev** [comment]
@llinros
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by fabianrenner** [comment]
When is this expected to be merged?

**Comment by karolcienkosz** [comment]
Hi, is there any chance for review?

**Review by apeabody — COMMENTED** [review]
Thanks for the contribution @llinros! - This looks good from a code review stand point. Ideally we should have an [test](https://github.com/terraform-google-modules/terraform-google-vm/tree/master/test/integration) exercise spot=true.

**Review by g-awmalik — APPROVED** [review]

**Pull request merged**
