### PR TITLE
Change absolute by relative paths in READMEs

### PR DESCRIPTION
**Pull request by yuryninog**
Regarding to issue #97 I think it is better to manage relative instead of absolute paths. In this way if you are located in a feature branch it is possible to navigate the files in the same branch.

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by morgante** [comment]
@yuryninog Unfortunately relative paths don't work when browsing the Terraform registry.

**Comment by yuryninog** [comment]
Hi @morgante 

Got it! thank you very much for your review ... 
Considering this, considering this ... Should we review the path in these files? They have a relative path:
* https://raw.githubusercontent.com/terraform-google-modules/terraform-google-vm/master/modules/instance_template/README.md
* https://raw.githubusercontent.com/terraform-google-modules/terraform-google-vm/master/modules/mig/README.md
* https://raw.githubusercontent.com/terraform-google-modules/terraform-google-vm/master/modules/preemptible_and_regular_instance_templates/README.md
Thanks in advance ...

**Comment by morgante** [comment]
Yes, absolute paths are preferred in docs but it's not really a top priority currently.

**Comment by bharathkkb** [comment]
Hi @yuryninog Closing this as not needed. Feel free to open another PR if you have bandwidth to covert those to absolute paths.

**Pull request closed without merging**
