### PR TITLE
fix!: add instances_details sensitive output

### PR DESCRIPTION
**Pull request by matusso**
Added sensitive = true for instances_details to avoid following error.
Error: Output refers to sensitive values
│
│   on outputs.tf line 22:
│   22: output "instances_details" {
│
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ confirm your intent.
│
│ If you do intend to export this data, annotate the output value as
│ sensitive by adding the following argument:
│     sensitive = true

### CODE REVIEW

**Review by ricicardo — APPROVED** [review]

**Comment by dennislapchenko** [comment]
Any plans to merge this soon?

**Comment by apeabody** [comment]
> Any plans to merge this soon?

Hi @matusso - Please visit https://cla.developers.google.com so we can review this PR.  Thanks!

**Comment by matusso** [comment]
done

**Comment by matusso** [comment]
could it be possible to finally close it? come on, I know u r big company, so you should be able to close one-line merge request

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @matusso!

**Pull request merged**
