### PR TITLE
fix: set target_size to null when autoscaling is enabled in MIG

### LINKED ISSUE #64: MIG: target_size being set when autoscaling is enabled
Hi

I am using the MIG module (v1.4.0) to manage instance groups with auto-scaling. The instance group has been up and running for some time and auto scaler kicked in, therefore increasing the number of instances above `min_replicas`. 

The problem is when I run `terraform apply` on a scaled up instance group, the module tries to set `target_size` to `min_replicas` ([code](https://github.com/terraform-google-modules/terraform-google-vm/blob/v1.4.0/modules/mig_with_percent/main.tf#L64)) and google throws an error about it:
> Error: Error resizing RegionInstanceGroupManager: googleapi: Error 412: Resizing of autoscaled regional managed instance groups is not allowed. If you want to manually adjust target size remove the autoscaler or set autoscaling policy mode to OFF., conditionNotMet

And as stated in the error, the `target_size` shouldn't be set at all when an autoscaler is attached to the instance group ([provider docs](https://www.terraform.io/docs/providers/google/r/compute_region_instance_group_manager.html#target_size)):
> This value should always be explicitly set unless this resource is attached to an autoscaler, in which case it should never be set.

This problem wouldn't show up if the group is at `min_replicas` scale, since no change would be calculated during the plan and the `target_size` value won't be set.

This would probably fix it:
> `target_size  = var.autoscaling_enabled ? var.min_replicas : var.target_size`
to

> `target_size  = var.autoscaling_enabled ? null : var.target_size`

### PR DESCRIPTION
**Pull request by ali-sattari**
Fixes #64

Signed-off-by: Ali Sattari <ali.sattari@gmail.com>

### CODE REVIEW

**Comment by ali-sattari** [comment]
@morgante when I try to see more details on that failed trigger by following the link to GCP build I get this:
>  You don't have permission to view builds and triggers in this project. 

Is there anyway I could see the details/output of failed test, short of setting up the test env locally?

**Comment by morgante** [comment]
Unfortunately the Cloud Build logs can't be shared publicly. This is the error I see there though:
```
system: Verifying

Profile: mig_autoscaler
Version: (not specified)
Target:  local://

  ×  MIG: Autoscaling Configuration (1 failed)
     ✔  Command: `gcloud --project=ci-vm-module-f9b5 compute instances list --format=json --filter='name~^mig-autoscaler*'` exit_status should eq 0
     ✔  Command: `gcloud --project=ci-vm-module-f9b5 compute instances list --format=json --filter='name~^mig-autoscaler*'` stderr should eq ""
     ×  Command: `gcloud --project=ci-vm-module-f9b5 compute instances list --format=json --filter='name~^mig-autoscaler*'` number of instances should be 4
```

**Comment by morgante** [comment]
This is the test that is failing: https://github.com/terraform-google-modules/terraform-google-vm/blob/master/test/integration/mig_autoscaler/controls/mig_autoscaler.rb#L38

I think you need to either update the test or (preferably) make sure that a *minimum* number of instances is created to start with the autoscaling group.

**Comment by ali-sattari** [comment]
I tried the other day to setup the test environment, but couldn't get it working over GCP with personal account (i.e no Gsuit/CLoud Identity hence no Org etc.)
I will give it another go, worst case I will make this PR a bit noisy by blackbox testing with Triggers.

**Comment by morgante** [comment]
@ali-sattari It's not strictly required to use `test/setup` for tests. If you have a project already, you can also try just creating a service account and giving it the owner role on your project then filling in `test/source.sh` with values like this:

```
export TF_VAR_project_id="my-project"
export SERVICE_ACCOUNT_JSON="(base64-encoded-key)
export TF_VAR_service_account='{email=\"$sa_email\", scopes = [\"cloud-platform\"]}'
```

**Comment by ali-sattari** [comment]
I was able to run tests with your hints in personal GCP account, thanks.
Tests fail as expected in non-interactive, however in interactive mode I could observe that instances were created after ~60 seconds, the amount of time could vary but it is not instant (probably a different behavior of GCE with `min_replicas` and `target_size`)

Running `kitchen_do verify` in interactive mode after 1-2 minutes of `kitchen_do converge` passes the tests:

```
-----> Starting Kitchen (v1.24.0)
-----> Setting up <mig-autoscaler-local>...
       Finished setting up <mig-autoscaler-local> (0m0.00s).
-----> Verifying <mig-autoscaler-local>...
$$$$$$ Running command `terraform workspace select kitchen-terraform-mig-autoscaler-local` in directory /workspace/test/fixtures/mig/autoscaler
$$$$$$ Running command `terraform output -json` in directory /workspace/test/fixtures/mig/autoscaler
system: Verifying

Profile: mig_autoscaler
Version: (not specified)
Target:  local://

  ✔  MIG: Autoscaling Configuration
     ✔  Command: `gcloud --project=terraform-tests-266616 compute instances list --format=json --filter='name~^mig-autoscaler*'` exit_status should eq 0
     ✔  Command: `gcloud --project=terraform-tests-266616 compute instances list --format=json --filter='name~^mig-autoscaler*'` stderr should eq ""
     ✔  Command: `gcloud --project=terraform-tests-266616 compute instances list --format=json --filter='name~^mig-autoscaler*'` number of instances should be 4
     ✔  Command: `gcloud --project=terraform-tests-266616 compute instance-groups list --format=json --filter='name~^mig-autoscaler*'` exit_status should eq 0
     ✔  Command: `gcloud --project=terraform-tests-266616 compute instance-groups list --format=json --filter='name~^mig-autoscaler*'` stderr should eq ""
     ✔  Command: `gcloud --project=terraform-tests-266616 compute instance-groups list --format=json --filter='name~^mig-autoscaler*'` number of instance groups should be 1
     ✔  Command: `gcloud --project=terraform-tests-266616 compute instance-groups managed list --format=json --filter='name~^mig-autoscaler*'` exit_status should eq 0
     ✔  Command: `gcloud --project=terraform-tests-266616 compute instance-groups managed list --format=json --filter='name~^mig-autoscaler*'` stderr should eq ""
     ✔  Command: `gcloud --project=terraform-tests-266616 compute instance-groups managed list --format=json --filter='name~^mig-autoscaler*'` number of instance groups should be 1
     ✔  Command: `gcloud --project=terraform-tests-266616 compute instance-groups managed list --format=json --filter='name~^mig-autoscaler*'` autoscaling should be enabled
     ✔  Command: `gcloud --project=terraform-tests-266616 compute instance-groups managed list --format=json --filter='name~^mig-autoscaler*'` autoscaler scaling policy minNumReplicas should be 4
     ✔  Command: `gcloud --project=terraform-tests-266616 compute instance-groups managed list --format=json --filter='name~^mig-autoscaler*'` autoscaler scaling policy cpuUtilization target should be 0.6


Profile Summary: 1 successful control, 0 control failures, 0 controls skipped
Test Summary: 12 successful, 0 failures, 0 skipped
       Finished verifying <mig-autoscaler-local> (0m5.43s).
```

As you suggested I will update the test to reflect this different behavior.

**Pull request merged**
