### PR TITLE
Add public IP support

### PR DESCRIPTION
**Pull request by rchenzheng**
- include examples
  - dynamic and static address
  - update readme

### CODE REVIEW

**Comment by rchenzheng** [comment]
Solves https://github.com/terraform-google-modules/terraform-google-vm/issues/80

**Comment by wkharold** [comment]
Please merge, this will allow ephemeral external IPs as well.

**Comment by mehdicopter** [comment]
When this is going to be merged ?

**Comment by bharathkkb** [comment]
Thanks for the PR @rchenzheng 

- Can we get tests passing for this? You can do `make docker_test_lint` to see what is failing for the lint check. I see that some docs also need to be regenerated. Please run `make build`. Additional details [here](https://github.com/terraform-google-modules/terraform-google-vm/blob/master/CONTRIBUTING.md).

- The simple example that was modified is also used in our integration tests [here](https://github.com/terraform-google-modules/terraform-google-vm/blob/master/test/fixtures/compute_instance/simple/main.tf). Since two variables was added to that example (`nat_ip` and `network_tier`) we will need to make adequate changes. Can we set some defaults, like `null` for `nat_ip` and `PREMIUM` for `network_tier` so that the example can get an ephemeral ip by default?

**Comment by bharathkkb** [comment]
@morgante wanted to confirm that we do want to add support for this in `compute_instance` module. The solution in #84 only works if the `instance_template` module is also used in conjunction.

**Comment by rchenzheng** [comment]
> Thanks for the PR @rchenzheng
> 
> * Can we get tests passing for this? You can do `make docker_test_lint` to see what is failing for the lint check. I see that some docs also need to be regenerated. Please run `make build`. Additional details [here](https://github.com/terraform-google-modules/terraform-google-vm/blob/master/CONTRIBUTING.md).
> * The simple example that was modified is also used in our integration tests [here](https://github.com/terraform-google-modules/terraform-google-vm/blob/master/test/fixtures/compute_instance/simple/main.tf). Since two variables was added to that example (`nat_ip` and `network_tier`) we will need to make adequate changes. Can we set some defaults, like `null` for `nat_ip` and `PREMIUM` for `network_tier` so that the example can get an ephemeral ip by default?

It's been quite hectic around here, I'll update the PR shortly

**Comment by morgante** [comment]
@rchenzheng Can you clarify if your use case is specifically to attach an external IP on the VM when the template doesn't have one? I'm not sure I fully follow the scenario where that's necessary.

**Comment by rchenzheng** [comment]
> @rchenzheng Can you clarify if your use case is specifically to attach an external IP on the VM when the template doesn't have one? I'm not sure I fully follow the scenario where that's necessary.

Yes attaching a static ip as indicated in https://github.com/terraform-google-modules/terraform-google-vm/issues/80

**Comment by morgante** [comment]
FYI this is the error in the test logs:
```
       Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].accessConfigs[0].natIP': 'null'. The specified external IP address 'null' was not found in region 'us-central1'., invalid
       
         on ../../../../modules/compute_instance/main.tf line 41, in resource "google_compute_instance_from_template" "compute_instance":
         41: resource "google_compute_instance_from_template" "compute_instance" {
       
       
       
       Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].accessConfigs[0].natIP': 'null'. The specified external IP address 'null' was not found in region 'us-central1'., invalid
       
         on ../../../../modules/compute_instance/main.tf line 41, in resource "google_compute_instance_from_template" "compute_instance":
         41: resource "google_compute_instance_from_template" "compute_instance" {
       
       
       
       Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].accessConfigs[0].natIP': 'null'. The specified external IP address 'null' was not found in region 'us-central1'., invalid
       
         on ../../../../modules/compute_instance/main.tf line 41, in resource "google_compute_instance_from_template" "compute_instance":
         41: resource "google_compute_instance_from_template" "compute_instance" {
       
       
       
       Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].accessConfigs[0].natIP': 'null'. The specified external IP address 'null' was not found in region 'us-central1'., invalid
       
         on ../../../../modules/compute_instance/main.tf line 41, in resource "google_compute_instance_from_template" "compute_instance":
         41: resource "google_compute_instance_from_template" "compute_instance" {
```

**Comment by rchenzheng** [comment]
> FYI this is the error in the test logs:
> 
> ```
>        Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].accessConfigs[0].natIP': 'null'. The specified external IP address 'null' was not found in region 'us-central1'., invalid
>        
>          on ../../../../modules/compute_instance/main.tf line 41, in resource "google_compute_instance_from_template" "compute_instance":
>          41: resource "google_compute_instance_from_template" "compute_instance" {
>        
>        
>        
>        Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].accessConfigs[0].natIP': 'null'. The specified external IP address 'null' was not found in region 'us-central1'., invalid
>        
>          on ../../../../modules/compute_instance/main.tf line 41, in resource "google_compute_instance_from_template" "compute_instance":
>          41: resource "google_compute_instance_from_template" "compute_instance" {
>        
>        
>        
>        Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].accessConfigs[0].natIP': 'null'. The specified external IP address 'null' was not found in region 'us-central1'., invalid
>        
>          on ../../../../modules/compute_instance/main.tf line 41, in resource "google_compute_instance_from_template" "compute_instance":
>          41: resource "google_compute_instance_from_template" "compute_instance" {
>        
>        
>        
>        Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.networkInterfaces[0].accessConfigs[0].natIP': 'null'. The specified external IP address 'null' was not found in region 'us-central1'., invalid
>        
>          on ../../../../modules/compute_instance/main.tf line 41, in resource "google_compute_instance_from_template" "compute_instance":
>          41: resource "google_compute_instance_from_template" "compute_instance" {
> ```

It's been fixed, thanks

**Pull request merged**
