### PR TITLE
fix #76 being unable to create a template with local-ssd

### LINKED ISSUE #76: Instance templates do not in their current form allow creation of scratch disks
Instance templates do not in their current form allow creation of scratch disks. The missing parameters mean that you end up defaulting to incompatible flags when you try to setup NVME, etc... I've submitted a PR (#75 ) that attempts to alleviate that problem by adding in the missing parameters.

### PR DESCRIPTION
**Pull request by homelessnessbo**
Signed-off-by: Ivan Kiselev <kiselev_ivan@pm.me>

### CODE REVIEW

**Comment by homelessnessbo** [comment]
@morgante I executed commands from the doc you posted

**Comment by homelessnessbo** [comment]
I have no permissions to see why it's failing

**Comment by morgante** [comment]
@homelessnessbo The contributing guide shows how to run the tests (linting and integration) locally. Please get those passing.

**Comment by bharathkkb** [comment]
@homelessnessbo I believe some unwanted source files may have been introduced?
I see `modules/instance_template/node_modules/*` and a `modules/instance_template/package-lock.json` in the diff.

In addition, we would also need to update the examples [here](https://github.com/terraform-google-modules/terraform-google-vm/blob/5a6ec12c3d26c88e45fe4b1a1d919562b4995f24/examples/instance_template/additional_disks/main.tf#L31)

**Comment by homelessnessbo** [comment]
So I tried to follow the steps in contributing guide, I provided SA I created with "Owner" and " Project Billing Manager" roles and I have this error now:


```
╰─$ make docker_test_prepare
docker run --rm -it \
		-e SERVICE_ACCOUNT_JSON \
		-e TF_VAR_org_id \
		-e TF_VAR_folder_id \
		-e TF_VAR_billing_account \
		-v "/Users/ivankiselev_/git/terraform-google-vm":/workspace \
		gcr.io/cloud-foundation-cicd/cft/developer-tools:0 \
		/usr/local/bin/execute_with_credentials.sh prepare_environment
Activated service account credentials for: [terraform-test-delete-me@mb-infrastructures-tst.iam.gserviceaccount.com]
Activated service account credentials for: [terraform-test-delete-me@mb-infrastructures-tst.iam.gserviceaccount.com]
Initializing modules...

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
module.project_ci_vm.module.project-factory.module.gcloud_deprivilege.random_id.cache: Refreshing state... [id=qQ7HcQ]
module.project_ci_vm.module.project-factory.module.gcloud_disable.random_id.cache: Refreshing state... [id=_seShw]
module.project_ci_vm.module.project-factory.null_resource.preconditions: Refreshing state... [id=9127562744135304984]
module.project_ci_vm.module.project-factory.module.gcloud_delete.random_id.cache: Refreshing state... [id=A0J9Gw]
module.project_ci_vm.module.project-factory.random_id.random_project_id_suffix: Refreshing state... [id=2Ho]
module.project_ci_vm.module.project-factory.module.gcloud_disable.null_resource.upgrade_destroy[0]: Refreshing state... [id=5948865453401742185]
module.project_ci_vm.module.project-factory.module.gcloud_disable.null_resource.decompress_destroy[0]: Refreshing state... [id=1408838915287691802]
module.project_ci_vm.module.project-factory.google_project.main: Creating...

Error: failed pre-requisites: missing permission on "billingAccounts/004079-99503E-5E46A8": billing.resourceAssociations.create

  on .terraform/modules/project_ci_vm/terraform-google-project-factory-7.1.0/modules/core_project_factory/main.tf line 96, in resource "google_project" "main":
  96: resource "google_project" "main" {


make: *** [docker_test_prepare] Error 1
```

**Pull request closed without merging**
